### PR TITLE
Corrections: typos in README. Also added the twitter icon in the footer.

### PR DESCRIPTION
**Pull request by RichGod93**
Was looking through the README and spotted some typos so I corrected them.

Also noticed the twitter icon in the footer wasn't displaying so I replaced it with the right file and added the alt text for the images

### CODE REVIEW

**Review by ALIPHATICHYD — APPROVED** [review]

**Review by ALIPHATICHYD — APPROVED** [review]

**Review by ALIPHATICHYD — COMMENTED** [review]
Duely noted

**Review by ALIPHATICHYD — APPROVED** [review]
Noted

**Review by ALIPHATICHYD — APPROVED** [review]
Noted

**Review by ALIPHATICHYD — APPROVED** [review]
Duely noted

**Comment by RichGod93** [comment]
Resolved conflicts

**Pull request merged**
